services:
  app:
    container_name: todo-app
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www/

  nginx:
    container_name: todo-app-nginx
    image: nginx:1.23.0-alpine
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
