version: '3.9'

services:
  app:
    container_name: todo-app
    environment:
      - APP_ENV=${APP_ENV}
      - MEMCACHED_USERNAME=${MEMCACHED_USERNAME}
      - MEMCACHED_PASSWORD=${MEMCACHED_PASSWORD}
      - MEMCACHED_SERVERS=${MEMCACHED_SERVERS}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - db_host=${DB_HOST}
        - db_port=${DB_PORT}
        - memcached_host=${MEMCACHED_HOST}
        - memcached_port=${MEMCACHED_PORT}
    working_dir: /var/www/
    depends_on:
      - postgres
      - memcached

  nginx:
    container_name: todo-app-nginx
    build:
      context: ./
      dockerfile: nginx.dockerfile
    # image: nginx:1.23.0-alpine
    ports:
      - 8080:80
    # volumes:
    #   - ./:/var/www/
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  postgres:
    container_name: todo-app-postgres
    image: postgres:14.4
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - 5432:5432

  memcached:
    container_name: todo-app-memcached
    image: memcached:1.6.15
    ports:
      - 11211:11211

  pgadmin:
    container_name: todo-app-pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - '8081:80'
    depends_on:
      - postgres
