services:
  todo-app-php-fpm:
    environment:
      - APP_ENV=${APP_ENV}
      - MEMCACHED_USERNAME=${MEMCACHED_USERNAME}
      - MEMCACHED_PASSWORD=${MEMCACHED_PASSWORD}
      - MEMCACHED_SERVERS=${MEMCACHED_SERVERS}
    build:
      context: ./
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - db_host=${DB_HOST}
        - db_port=${DB_PORT}
        - memcached_host=${MEMCACHED_HOST}
        - memcached_port=${MEMCACHED_PORT}
    restart: always
    networks:
      - todo-app
    depends_on:
      todo-app-postgres:
        condition: service_started
      todo-app-memcached:
        condition: service_started

  todo-app-nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    restart: always
    networks:
      - todo-app
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      todo-app-php-fpm:
        condition: service_started

  todo-app-postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - todo-app-data:/var/lib/postgresql/data
    networks:
      - todo-app

  todo-app-memcached:
    image: memcached:1.6.15
    ports:
      - 11211:11211
    networks:
      - todo-app

networks:
  todo-app:

volumes:
  todo-app-data:
